sources:
  - name: raw 
    schema: gz_raw_data
    description: raw data from greenweez
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: raw sales data
      - name: product
        identifier: raw_gz_product
        description: raw product data
      - name: ship
        identifier: raw_gz_ship
        description: raw shipping data
