sources:
  - name: raw 
    schema: gz_raw_data
    description: raw data from greenweez
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Greenweez sales data / we have on row per product_id found in each orders_id
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness: 
          warn_after: {count: 90, period: day} 
      - name: product
        identifier: raw_gz_product
        description: Greenweez product data / we have per product_id the purchase_price
        columns:
          - name: products_id
            description: primary key of the table 
            tests:
              - unique   
              - not_null
      - name: ship
        identifier: raw_gz_ship
        description: Greenweez shipping data / we have shipping data on row per orders_id
        columns:
          - name: orders_id
            description: primary key of the table 
            tests:
              - unique
              - not_null

      - name: adwords
        identifier: raw_gz_adwords
        description: adwords ad campaign details 
        tests:
          - unique:
              column_name: "( || '-' || )"
          - not_null
      - name: bing
        identifier: raw_gz_bing
        description: bing ad campaign details
        tests:
          - unique:
              column_name: "( || '-' || )"
          - not_null
      - name: criteo
        identifier: raw_gz_criteo
        description: criteo ad campaign details
        tests:
          - unique:
              column_name: "( || '-' || )"
          - not_null
      - name: facebook
        identifier: raw_gz_facebook
        description: facebook ad campaign details
        tests:
          - unique:
              column_name: "( || '-' || )"
          - not_null